### ISSUE TITLE
Вопросы по ДЗ с pytest

### ISSUE THREAD

**Issue by plaksacarp** [plaksacarp/18-11-22-#1]
##### Вопросы: 
1. В PyCharm не удалось запустить тест из папки Tests. Выдавал ошибку – не видит модуль, который нужно тестировать.
1. Хотела удалить main.py, т.к. это копия файла предыдущего проекта, в этом проекте не нужен. Но PyCharm не дал удалить. Скриншот ошибки:
![screenshot 2018-11-23 00 25 17](https://user-images.githubusercontent.com/44879709/48925460-c3c8e300-eed4-11e8-9e07-d20a6f18bf5d.jpg)

1. Во время установки Git на ПК вышло сообщение - на скриншоте. На что это повлияет?
![screenshot 2018-11-23 02 57 35_](https://user-images.githubusercontent.com/44879709/48925466-e22ede80-eed4-11e8-9003-b4ad2dde9cb1.jpg)

1. При создании локального репозитория использовала "git add . " Добавились все файлы, в том числе ненужное (папка .idea, вордовский файл, рисунки jpeg). Существует команда, чтобы убрать эти файлы/папки из отслеживания?

**Comment by coursar** [comment]
По поводу команды:
```shell
git rm -r <через пробел имена каталогов и файлов>
git commit -m "сообщение"
```

**Comment by coursar** [comment]
Лучшее правило: один вопрос - один issue. По поводу PyTest - структуру брали такую, как на лекции была? Вечером смогу детальнее посмотреть.

**Comment by coursar** [comment]
По поводу 3 вопроса - это редактор, который будет вызываться при коммите, если вы не укажете флаг -m "Сообщение коммита"

**Comment by coursar** [comment]
Структуру вам надо взять из лекций, где у нас были package с файликами __init__.py и не забывать про .gitignore. Проще создать новый репозиторий, чем из этого удалять старые файлы.

**Comment by coursar** [comment]
@plaksacarp, поправил структуру. В VCS не нужно хранить картинки, .idea, документы (если они не постоянные) и прочие временные файлы.
